# Generated by Django 2.0 on 2018-03-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=40)),
                ('language', models.CharField(max_length=20)),
                ('contributor', models.CharField(max_length=40)),
                ('forks', models.IntegerField()),
            ],
        ),
    ]
