# Generated by Django 2.0 on 2018-04-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_num', models.IntegerField()),
                ('dep_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(max_length=8)),
                ('sex', models.CharField(max_length=1)),
                ('relationship', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Dependent')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.IntegerField()),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('dnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30)),
                ('pro_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Workfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Department')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Workson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('em_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Employee')),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Projects')),
            ],
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='ticker',
            new_name='ticker_name',
        ),
        migrations.AddField(
            model_name='dependent_of',
            name='ep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Employee'),
        ),
        migrations.AddField(
            model_name='dependent',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Employee'),
        ),
        migrations.AddField(
            model_name='controls',
            name='dep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Department'),
        ),
        migrations.AddField(
            model_name='controls',
            name='proj_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Projects'),
        ),
    ]
